all: matrice.c niti.c zadatak1.c zadatak2.c
	gcc matrice.c -o matrice -pthread
	gcc niti.c -o niti -pthread
	gcc zadatak1.c -o zadatak1 -pthread
	gcc zadatak2.c -o zadatak2 -pthread

clean:
	rm niti
	rm matrice
	rm zadatak1
	rm zadatak2